## Step 1: Data preprocessing

In [2]:
# https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/a8b3293a-bb3e-4247-927e-739fbf3f5515/lessons/d74891dc-49c8-4569-9cab-6d508083e841/concepts/36be59a4-aca3-4281-9c47-2b695de95a46
import time
from collections import namedtuple

import numpy as np
import tensorflow as tf

In [4]:
'''
Loading the text data
'''
with open('anna.txt', 'r') as f:
    text=f.read()

# get the character vocabulary set
vocab = set(text)
vocab

{'\n',
 ' ',
 '!',
 '"',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 ',',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '?',
 '@',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z'}

In [5]:
# character : integer dictionary
vocab_to_int = {c: i for i, c in enumerate(vocab)}
vocab_to_int

{'\n': 21,
 ' ': 23,
 '!': 11,
 '"': 29,
 '$': 26,
 '%': 67,
 '&': 3,
 "'": 0,
 '(': 20,
 ')': 56,
 '*': 34,
 ',': 77,
 '-': 4,
 '.': 43,
 '/': 62,
 '0': 60,
 '1': 76,
 '2': 72,
 '3': 7,
 '4': 73,
 '5': 2,
 '6': 32,
 '7': 51,
 '8': 78,
 '9': 30,
 ':': 14,
 ';': 44,
 '?': 24,
 '@': 31,
 'A': 64,
 'B': 16,
 'C': 57,
 'D': 70,
 'E': 17,
 'F': 25,
 'G': 28,
 'H': 39,
 'I': 49,
 'J': 40,
 'K': 33,
 'L': 1,
 'M': 9,
 'N': 48,
 'O': 36,
 'P': 65,
 'Q': 66,
 'R': 79,
 'S': 58,
 'T': 6,
 'U': 27,
 'V': 8,
 'W': 35,
 'X': 75,
 'Y': 68,
 'Z': 59,
 '_': 71,
 '`': 81,
 'a': 80,
 'b': 82,
 'c': 50,
 'd': 55,
 'e': 18,
 'f': 41,
 'g': 54,
 'h': 45,
 'i': 19,
 'j': 38,
 'k': 10,
 'l': 53,
 'm': 42,
 'n': 61,
 'o': 74,
 'p': 5,
 'q': 47,
 'r': 12,
 's': 15,
 't': 69,
 'u': 52,
 'v': 63,
 'w': 13,
 'x': 37,
 'y': 46,
 'z': 22}

In [6]:
# integer : character dictionary
int_to_vocab = dict(enumerate(vocab))
int_to_vocab

{0: "'",
 1: 'L',
 2: '5',
 3: '&',
 4: '-',
 5: 'p',
 6: 'T',
 7: '3',
 8: 'V',
 9: 'M',
 10: 'k',
 11: '!',
 12: 'r',
 13: 'w',
 14: ':',
 15: 's',
 16: 'B',
 17: 'E',
 18: 'e',
 19: 'i',
 20: '(',
 21: '\n',
 22: 'z',
 23: ' ',
 24: '?',
 25: 'F',
 26: '$',
 27: 'U',
 28: 'G',
 29: '"',
 30: '9',
 31: '@',
 32: '6',
 33: 'K',
 34: '*',
 35: 'W',
 36: 'O',
 37: 'x',
 38: 'j',
 39: 'H',
 40: 'J',
 41: 'f',
 42: 'm',
 43: '.',
 44: ';',
 45: 'h',
 46: 'y',
 47: 'q',
 48: 'N',
 49: 'I',
 50: 'c',
 51: '7',
 52: 'u',
 53: 'l',
 54: 'g',
 55: 'd',
 56: ')',
 57: 'C',
 58: 'S',
 59: 'Z',
 60: '0',
 61: 'n',
 62: '/',
 63: 'v',
 64: 'A',
 65: 'P',
 66: 'Q',
 67: '%',
 68: 'Y',
 69: 't',
 70: 'D',
 71: '_',
 72: '2',
 73: '4',
 74: 'o',
 75: 'X',
 76: '1',
 77: ',',
 78: '8',
 79: 'R',
 80: 'a',
 81: '`',
 82: 'b'}

In [8]:
'''
convert characters to integers using the charater:integer dictionary
'''
chars = np.array([vocab_to_int[c] for c in text], dtype=np.int32)
chars

array([57, 45, 80, ..., 10, 15, 43], dtype=int32)

In [9]:
# First 100 chars in text
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

In [10]:
# First 100 characters converted to integers
chars[:100]

array([57, 45, 80,  5, 69, 18, 12, 23, 76, 21, 21, 21, 39, 80,  5,  5, 46,
       23, 41, 80, 42, 19, 53, 19, 18, 15, 23, 80, 12, 18, 23, 80, 53, 53,
       23, 80, 53, 19, 10, 18, 44, 23, 18, 63, 18, 12, 46, 23, 52, 61, 45,
       80,  5,  5, 46, 23, 41, 80, 42, 19, 53, 46, 23, 19, 15, 23, 52, 61,
       45, 80,  5,  5, 46, 23, 19, 61, 23, 19, 69, 15, 23, 74, 13, 61, 21,
       13, 80, 46, 43, 21, 21, 17, 63, 18, 12, 46, 69, 45, 19, 61], dtype=int32)

In [20]:
# Length of the chars list. This will give the total number of numbers in the list
chars.shape

(1985222,)

In [12]:
def split_data(chars, batch_size, num_steps, split_frac=0.9):
    """ 
    Split character data into training and validation sets, inputs and targets for each set.
    
    Arguments
    ---------
    chars: character array
    batch_size: Size of examples in each of batch
    num_steps: Number of sequence steps to keep in the input and pass to the network
    split_frac: Fraction of batches to keep in the training set
    
    
    Returns train_x, train_y, val_x, val_y
    """
    # num_steps: Sequence length of characters we are going to pass into the network.
    #            The longer the sequence is, the further back it can look for correlations between characters.   
    # Eg: 100 numbers in the chars list, batch_size = 10, num_steps = 1
    # Eg: slice_size = 10 * 1 = 10
    slice_size = batch_size * num_steps
    # Get the total number of batches we would get from the data 
    # by dividing total number of numbers(words) by the size of each slice(words in each slice)
    # Eg: n_batches = 100/10 = 10 batches
    n_batches = int(len(chars) / slice_size)
    
    # Drop the last few characters to make only full batches
    # Eg: x = chars[:10]
    x = chars[: n_batches*slice_size]
    # Our target variable is one value ahead of the feature 
    # Eg: y = chars[1:11]
    y = chars[1: n_batches*slice_size + 1]
    
    # Split the data into batch_size slices, then stack them into a 2D matrix 
    # This is vertically stacked data.
    # rows = batch_size, columns = rest of the data. width is the number of steps in the sequence
    x = np.stack(np.split(x, batch_size))
    y = np.stack(np.split(y, batch_size))
    # Now x and y are arrays with dimensions (batch_size x n_batches*num_steps)
    
    # Split into training and validation sets, keep the first split_frac batches for training
    split_idx = int(n_batches*split_frac)
    
    # training set
    train_x, train_y = x[:, :split_idx*num_steps], y[:, :split_idx*num_steps]
    # validation set
    val_x, val_y = x[:, split_idx*num_steps:], y[:, split_idx*num_steps:]
    
    return train_x, train_y, val_x, val_y

In [31]:
# batch_size = 10, num_steps = 50
train_x, train_y, val_x, val_y = split_data(chars, 10, 50)
# rows = batch_size
train_x.shape

(10, 178650)

In [32]:
'''
Sample showing the working of numpy stack
'''
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.stack((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

In [33]:
'''
Sample showing the working of numpy split - splits array into multiple sub arrays
'''
c = np.arange(9.0)
print(c)
print(np.split(c, 3))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.]
[array([ 0.,  1.,  2.]), array([ 3.,  4.,  5.]), array([ 6.,  7.,  8.])]


In [34]:
# Returning all batches for first 15 steps
train_x[:, :15]

array([[57, 45, 80,  5, 69, 18, 12, 23, 76, 21, 21, 21, 39, 80,  5],
       [23, 80, 42, 23, 61, 74, 69, 23, 54, 74, 19, 61, 54, 23, 69],
       [63, 19, 61, 43, 21, 21, 29, 68, 18, 15, 77, 23, 19, 69,  0],
       [61, 23, 55, 52, 12, 19, 61, 54, 23, 45, 19, 15, 23, 50, 74],
       [23, 19, 69, 23, 19, 15, 77, 23, 15, 19, 12, 11, 29, 23, 15],
       [23, 49, 69, 23, 13, 80, 15, 21, 74, 61, 53, 46, 23, 13, 45],
       [45, 18, 61, 23, 50, 74, 42, 18, 23, 41, 74, 12, 23, 42, 18],
       [44, 23, 82, 52, 69, 23, 61, 74, 13, 23, 15, 45, 18, 23, 13],
       [69, 23, 19, 15, 61,  0, 69, 43, 23,  6, 45, 18, 46,  0, 12],
       [23, 15, 80, 19, 55, 23, 69, 74, 23, 45, 18, 12, 15, 18, 53]], dtype=int32)

In [35]:
'''
Function to grab batches out of the arrays made by split_data. 
Here each batch will be a sliding window on these arrays with size batch_size X num_steps. 
For example, if we want our network to train on a sequence of 100 characters, 
num_steps = 100. For the next batch, we'll shift this window the next sequence of num_steps 
characters. In this way we can feed batches to the network and the cell states will 
continue through on each batch.
'''
def get_batch(arrs, num_steps):
    
    batch_size, slice_size = arrs[0].shape
    
    n_batches = int(slice_size/num_steps)
    
    for b in range(n_batches):
        yield [x[ : , b*num_steps : (b+1)*num_steps] for x in arrs]

## Step 2: RNN model building

In [36]:
def build_rnn(num_classes, 
              batch_size=50, 
              num_steps=50, 
              lstm_size=128, 
              num_layers=2,
              learning_rate=0.001, 
              grad_clip=5, 
              sampling=False):
    
    # When we're using this network for sampling later, we'll be passing in
    # one character at a time, so providing an option for that
    if sampling == True:
        batch_size, num_steps = 1, 1

    tf.reset_default_graph()
    
    # Declare placeholders we'll feed into the graph
    inputs = tf.placeholder(tf.int32, 
                            [batch_size, num_steps], 
                            name='inputs')
    targets = tf.placeholder(tf.int32, 
                             [batch_size, num_steps], 
                             name='targets')
    
    # Keep probability placeholder for drop out layers
    keep_prob = tf.placeholder(tf.float32, 
                               name='keep_prob')
    
    # One-hot encoding the input and target characters
    x_one_hot = tf.one_hot(inputs, 
                           num_classes)
    y_one_hot = tf.one_hot(targets, 
                           num_classes)
    
    ### Build the RNN layers
    # Use a basic LSTM cell
    lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
    
    # Add dropout to the cell
    drop = tf.contrib.rnn.DropoutWrapper(lstm, 
                                         output_keep_prob = keep_prob)
    
    # Stack up multiple LSTM layers, for deep learning
    cell = tf.contrib.rnn.MultiRNNCell([drop] * num_layers)
    # Setting the cell state to 0
    initial_state = cell.zero_state(batch_size, tf.float32)
    
    ### Run the data through the RNN layers
    # This makes a list where each element is one step in the sequence
    rnn_inputs = [tf.squeeze(i, squeeze_dims=[1]) for i in tf.split(x_one_hot, num_steps, 1)]
    
    # Run each sequence step through the RNN and collect the outputs
    # outputs is the outputs of the hidden layer for each step in the sequence
    outputs, state = tf.contrib.rnn.static_rnn(cell, 
                                               rnn_inputs, 
                                               initial_state=initial_state)
    final_state = state
    
    # Reshape output so it's a bunch of rows, one output row for each step for each batch
    seq_output = tf.concat(outputs, 
                           axis=1)
    # Each row is one output. lstm_size is the number of hidden layers in our cells
    # The number of columns or width of output is the number of hidden layers in the cells - lstm_size
    output = tf.reshape(seq_output, 
                        [-1, lstm_size])
    
    # Now connect the RNN outputs to a softmax layer
    with tf.variable_scope('softmax'):
        # Weights
        softmax_w = tf.Variable(tf.truncated_normal((lstm_size, num_classes), 
                                                    stddev=0.1))
        # Biases
        softmax_b = tf.Variable(tf.zeros(num_classes))
        
    # Since output is a bunch of rows of RNN cell outputs, logits will be a bunch
    # of rows of logit outputs, one for each step and batch
    logits = tf.matmul(output, softmax_w) + softmax_b
    
    # Use softmax to get the probabilities for predicted characters
    preds = tf.nn.softmax(logits, 
                          name='predictions')
    
    # Reshape the targets to match the logits
    y_reshaped = tf.reshape(y_one_hot, 
                            [-1, num_classes])
    loss = tf.nn.softmax_cross_entropy_with_logits(logits = logits, 
                                                   labels = y_reshaped)
    cost = tf.reduce_mean(loss)
    
    # Optimizer for training, using gradient clipping to control exploding gradients
    tvars = tf.trainable_variables()
    grads, _ = tf.clip_by_global_norm(tf.gradients(cost, tvars), 
                                      grad_clip)
    train_op = tf.train.AdamOptimizer(learning_rate)
    optimizer = train_op.apply_gradients(zip(grads, tvars))
    
    # Export the nodes
    export_nodes = ['inputs', 'targets', 'initial_state', 'final_state',
                    'keep_prob', 'cost', 'preds', 'optimizer']
    Graph = namedtuple('Graph', 
                       export_nodes)
    local_dict = locals()
    graph = Graph(*[local_dict[each] for each in export_nodes])
    
    return graph

In [38]:
'''
batch_size - Number of sequences running through the network in one pass.

num_steps - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.

lstm_size - The number of units in the hidden layers.

num_layers - Number of hidden LSTM layers to use

learning_rate - Learning rate for training

keep_prob - The dropout keep probability when training. If you're network is overfitting, try decreasing this.
'''
batch_size = 100
num_steps = 100 
lstm_size = 512
num_layers = 2
learning_rate = 0.001
keep_prob = 0.5

## Step 3: Training model

In [39]:
epochs = 1
# Save every N iterations
save_every_n = 200
train_x, train_y, val_x, val_y = split_data(chars, batch_size, num_steps)

model = build_rnn(len(vocab), 
                  batch_size=batch_size,
                  num_steps=num_steps,
                  learning_rate=learning_rate,
                  lstm_size=lstm_size,
                  num_layers=num_layers)

saver = tf.train.Saver(max_to_keep=100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    # Use the line below to load a checkpoint and resume training
    #saver.restore(sess, 'checkpoints/______.ckpt')
    
    n_batches = int(train_x.shape[1]/num_steps)
    iterations = n_batches * epochs
    for e in range(epochs):
        
        # Train network
        new_state = sess.run(model.initial_state)
        loss = 0
        for b, (x, y) in enumerate(get_batch([train_x, train_y], num_steps), 1):
            iteration = e*n_batches + b
            start = time.time()
            feed = {model.inputs: x,
                    model.targets: y,
                    model.keep_prob: keep_prob,
                    model.initial_state: new_state}
            
            batch_loss, new_state, _ = sess.run([model.cost, model.final_state, model.optimizer], 
                                                 feed_dict=feed)
            loss += batch_loss
            end = time.time()
            
            print('Epoch {}/{} '.format(e+1, epochs),
                  'Iteration {}/{}'.format(iteration, iterations),
                  'Training loss: {:.4f}'.format(loss/b),
                  '{:.4f} sec/batch'.format((end-start)))
        
            
            if (iteration%save_every_n == 0) or (iteration == iterations):
                # Check performance, notice dropout has been set to 1
                val_loss = []
                new_state = sess.run(model.initial_state)
                for x, y in get_batch([val_x, val_y], num_steps):
                    feed = {model.inputs: x,
                            model.targets: y,
                            model.keep_prob: 1.,
                            model.initial_state: new_state}
                    batch_loss, new_state = sess.run([model.cost, model.final_state], feed_dict=feed)
                    val_loss.append(batch_loss)

                print('Validation loss:', np.mean(val_loss),
                      'Saving checkpoint!')
                saver.save(sess, "checkpoints/i{}_l{}_v{:.3f}.ckpt".format(iteration, lstm_size, np.mean(val_loss)))

Epoch 1/1  Iteration 1/178 Training loss: 4.4206 11.8804 sec/batch
Epoch 1/1  Iteration 2/178 Training loss: 4.3760 8.6766 sec/batch
Epoch 1/1  Iteration 3/178 Training loss: 4.2257 7.5384 sec/batch
Epoch 1/1  Iteration 4/178 Training loss: 4.5049 9.2701 sec/batch
Epoch 1/1  Iteration 5/178 Training loss: 4.4487 7.6899 sec/batch


KeyboardInterrupt: 

In [ ]:
tf.train.get_checkpoint_state('checkpoints')

In [ ]:

def sample(checkpoint, n_samples, lstm_size, vocab_size, prime="The "):
    samples = [c for c in prime]
    model = build_rnn(vocab_size, lstm_size=lstm_size, sampling=True)
    saver = tf.train.Saver()
    with tf.Session() as sess:
        saver.restore(sess, checkpoint)
        new_state = sess.run(model.initial_state)
        for c in prime:
            x = np.zeros((1, 1))
            x[0,0] = vocab_to_int[c]
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.preds, model.final_state], 
                                         feed_dict=feed)

        c = pick_top_n(preds, len(vocab))
        samples.append(int_to_vocab[c])

        for i in range(n_samples):
            x[0,0] = c
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.preds, model.final_state], 
                                         feed_dict=feed)

            c = pick_top_n(preds, len(vocab))
            samples.append(int_to_vocab[c])
        
    return ''.join(samples)

In [ ]:
checkpoint = "checkpoints/____.ckpt"
samp = sample(checkpoint, 2000, lstm_size, len(vocab), prime="Far")
print(samp)